### ISSUE TITLE
Update of Weight categories standardisation in LB declaration

### ISSUE THREAD

**Issue by Antoine-Duparc** [OB7-IRD/t3#102]
AMexpert encounter more and more new weight category + 60kg for the major tuna species. 

Process level 1.3 (and other?) have to be updates accordingly to treat this new income.

**Comment by Antoine-Duparc** [comment]
This issues was also raised by Pascal. He added new weight categories (code 14) in the ref table of observe ps.common.weightcategory (YFT+60 ; BET+60 ; ALB +60).

process 1.3 of T3R have to be updated accordingly. The ref table seems not to be intern to the package. loading from db or wirting in the code (make a ref table in that case).

As instance, in 2024 AO, I got the corresponding error message.

2024-10-14 09:50:49 - Ongoing process 1.3 on item "4".
[trip: fr.ird.data.ps.common.Trip#1712047836714#0.8200906384283725]
Erreur dans object_full_trips$conversion_weigth_category(global_output_path = final_output_path,  : 
  2024-10-14 09:50:49 - Logbook category 14 not set in the algorithm.
[trip: fr.ird.data.ps.common.Trip#1712047836714#0.8200906384283725, activity: fr.ird.data.ps.logbook.Activity#1712059141442#0.17245577660559497, elementarycatch: fr.ird.data.ps.logbook.Catch#1712059194591#0.5556927070390921]

**Comment by Antoine-Duparc** [comment]
I think we just need to add code 14 to the line 1440 (} else if (current_weight_category_code %in% c(5, 7, 8, 13)) {)

**Comment by JeanneClement** [comment]
I've added weight code 14 in full_trips and in the correspondence table in part 1.3  of level1.Rmd, with the standardised label >30kg for  free object school in OA and >10kg for for floating object school in the Atlantic Ocean and for undetermined, free and floating object school in the Indian Ocean. I have executed T3 on 2024 OA without error but I will add a weight label matching table in inst/.

**Comment by JeanneClement** [comment]
"I've added weight code 14 in full_trips and in the correspondence table in part 1.3  of level1.Rmd, with the standardised label >30kg for  free object school in OA and >10kg for for floating object school in the Atlantic Ocean and for undetermined, free and floating object school in the Indian Ocean. I have executed T3 until level 1.4 on 2024 OA without error but I will add a weight label matching table in inst/.
