### ISSUE TITLE
Extract data references from the code

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#107]
In fact, the data references used in Process 1.5 are hard-coded.
The idea is to place this data in an external file and give it to the script as an argument.

**Comment by JulienLebranchu** [comment]
Following a discussion with @Antoine-Duparc , we can add an argument in configuration file to surcharge the path file which is in the package.

**Comment by JeanneClement** [comment]
It's done, I think. Mathieu added the table set_duration_ref.csv in the package. Can I close this issue ?
