### ISSUE TITLE
lack of reference NEI flags

### ISSUE THREAD

**Issue by VanessaRojo** [OB7-IRD/t3#123]
Until 2018 the Avdth bd included ESP and other associated flags c("ESP", "GTM", "CUW", "SLV", "PAN", "BLZ").
The references are missing in order to be able to use the samples of these flags.

2024-04-10 14:59:52 - Error: invalid "set_duration_ref" argument.
No correspondance with activity parameters (ocean and/or school type).
[trip: fr.ird.avdth.entities.data.Trip#0630#20180129, activity: fr.ird.avdth.entities.data.Activity#0630#201801292017122401]
Error in object_full_trips$set_duration(set_duration_ref = object_model_data$.__enclos_env__$private$setdurationrefs,  :

**Comment by VanessaRojo** [comment]
> Until 2018 the Avdth bd included ESP and other associated flags c("ESP", "GTM", "CUW", "SLV", "PAN", "BLZ"). The references are missing in order to be able to use the samples of these flags.
> 
> 2024-04-10 14:59:52 - Error: invalid "set_duration_ref" argument. No correspondance with activity parameters (ocean and/or school type). [trip: fr.ird.avdth.entities.data.Trip#0630#20180129, activity: fr.ird.avdth.entities.data.Activity#0630#201801292017122401] Error in object_full_trips$set_duration(set_duration_ref = object_model_data$.**enclos_env**$private$setdurationrefs, :

**Comment by Antoine-Duparc** [comment]
@MathieuDepetris 
La liste des pays est fermé. ne serait il pas possible de mettre un code de warning avec une valeur par défaut au lieu de faire des copié collé de ref. Mettre par exmple la liste des NEI a traiter comme l'espagne et idem pour l'Iatlie pour la france?
