### ISSUE TITLE
Set duration NA

### ISSUE THREAD

**Issue by Antoine-Duparc** [OB7-IRD/t3#129]
A vérifier : 
- soit c'est une erreur dans les données
- soit il y a une capture nulle donc il faudrait mettre l'intercept comme valeur de set duration et pas NA

Solution : renforcer le contrôle pour différencier les captures = 0 avec calée nulle des cas qui demande une correction (calée positive ou absence de déclaration.

Run T3 AO 2020

  2024-10-02 08:46:17 - Set declared as fishing operation but without elementary catch associated. Set duration define as NA.
[trip: fr.ird.data.ps.common.Trip#1708006009143#1875.1710859906332174, activity: fr.ird.data.ps.logbook.Activity#1708006009143#81715.9555285773382154]

**Comment by JeanneClement** [comment]
C'était une erreur dans les données qui a été corrigée j'ai l'impression, je n'ai plus ce message pour ce trip et cette activité et une valeur de 141min pour set_duration. Je vais quand même préciser dans le message : "Set declared as **successful** fishing operation but without elementary catch associated. Set duration define as NA" et je vais changer l'unité de set duration de min à heures pour unformiser avec les autres durées.
