### ISSUE TITLE
Sphinx issue

### ISSUE THREAD

**Issue by Antoine-Duparc** [OB7-IRD/t3#30]
**Describe the bug**
installation failed

**To Reproduce**
> library(devtools)
Le chargement a nécessité le package : usethis
>  devtools::install_github("https://github.com/OB7-IRD/t3")
Downloading GitHub repo OB7-IRD/t3@HEAD
"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:OB7-IRD/sphinx_ob7_theme.git C:\Users\aduparc\AppData\Local\Temp\RtmpWI2H4o\remotes153c198e3903/OB7-IRD-t3-b2d0754/docsrc/source/_themes/sphinx_ob7_theme
Erreur : Failed to install 't3' from GitHub:
  Command failed (128)
De plus : Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  l'exécution de la commande '"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules git@github.com:OB7-IRD/sphinx_ob7_theme.git C:\Users\aduparc\AppData\Local\Temp\RtmpWI2H4o\remotes153c198e3903/OB7-IRD-t3-b2d0754/docsrc/source/_themes/sphinx_ob7_theme' renvoie un statut 128

**Expected behavior**
I want to install T3 please ;)

**Comment by JulienLebranchu** [comment]
The error comes from the version of git on windows. I avoid it by moving the documentation files to a new branch
