### ISSUE TITLE
Create SQL query to AVDTH database

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#42]
Adapt the SQL query from T3 to AVDTH :

- [x] t3_activities.sql
- [x] t3_elementarycatch.sql
- [x] t3_elementarylanding.sql
- [x] t3_lengthstep.sql
- [x] t3_lengthweightrelationship.sql
- [x] t3_samples.sql
- [x] t3_sampleset.sql
- [x] t3_setdurationref.sql
- [x] t3_trip.sql
- [x] t3_wellplan.sql

**Comment by laurentfloch** [comment]
Pour tous les scripts, je n’ai pas converti la restriction AND t.topiaid IN (?trips_selected) pour la base AVDTH qui est certainement liée au script R qui encapsulera les requêtes SQL. 
A confirmer ?

A l’occasion de la conversion en AVDTH des requêtes pour T3+, j’ai évidemment effectué une vérification des résultats ce qui m’a permis de détecter certains problèmes au niveau du modèle de données et du contenu de certaines tables de références.

Ci-dessous, le bilan pour chaque requête :

t3_activities.sql
	OK
t3_elementarycatch.sql 
	OK
t3_elementarylanding.sql
	OK
t3_lengthstep.sql
	NOK
Le nom de cette table correspond à un pas de mesure pour les longueurs alors que le contenu correspond aux paramètres de conversion LD1-LF
	La table de T3 n’est pas complète, voir ticket :
	https://github.com/OB7-IRD/t3/issues/46
t3_lengthweightrelationship.sql
	NOK
	Les paramètres ne sont pas identiques en T3+ et T3 fortran.
	La mise à jour sera réalisée ultérieurement.
t3_samples.sql
	NOK
	Problème de type de données dans la table de t3+, voir ticket ci-dessous
https://github.com/OB7-IRD/t3/issues/45
t3_sampleset.sql
	OK
t3_setdurationref.sql
	NOK
	Le fichier t3+ setdurations.xls pour les paramètres des calées n’est pas identique au fichier t3 fortran.
	La mise à jour sera réalisée ultérieurement.
t3_trip.sql
	OK
t3_wellplan.sql
	OK

**Comment by laurentfloch** [comment]
[t3r.zip](https://github.com/OB7-IRD/t3/files/5895557/t3r.zip)
