### ISSUE TITLE
Add new values for set duration referencies

### ISSUE THREAD

**Issue by MathieuDepetris** [OB7-IRD/t3#43]
For now, values for 2020 are missing in the t3 database set duration reference table.
For patch temporary the process (and don't oblige it to stop for year 2019), fake references are added in the code.
Don't forget to remove it after update of the t3 set duration reference table.

**Comment by laurentfloch** [comment]
La mise à jour a été réalisée à l'aide du script R 10-update-setduration-t3.
[setdurations.xlsx](https://github.com/OB7-IRD/t3/files/5783283/setdurations.xlsx)
