### ISSUE TITLE
Create new length step value for BET of 55 cm (in LD1)

### ISSUE THREAD

**Issue by MathieuDepetris** [OB7-IRD/t3#44]
Data of a BET measured 55 cm in LD1 was detected in the t3 database (for 2008 in the Indian Ocean samples).
In waiting to database references update, manual value was added in the code.
Don't forget to remove it after updating reference tables in the database.

**Comment by laurentfloch** [comment]
Il convient de vérifier que ce ne soit pas une erreur dans les données.
En effet, cette valeur n'est pas dans la matrice de conversion des longueurs dorsales en longueur fourche.

**Comment by laurentfloch** [comment]
La matrice de conversion ci-jointe contient des valeurs jusqu'à 600 mm pour le BET.
I convient de vérifier avec Pascal Cauquil sur la raison de cette limitation dans t3+.

[ld1lfall.xlsx](https://github.com/OB7-IRD/t3/files/5782188/ld1lfall.xlsx)

**Comment by pascalcauquil** [comment]
Lors du développement de t3+ "on" nous avait fourni une matrice (dite clé) de conversion fausse !
Pour certains espèces/océan/LD1, la somme des proportions réparties ne faisaient pas 100% ! Et on mis du temps à s'en rendre compte.

On nous avait alors fourni une clé valide dans un second temps. On a dû refaire un import, avec un format de fichier différent : no comment

Alors si dans le référentiel actuel de la base cela s'arrête à 50 ou 55 cm (?), c'est que cette seconde clé que l'on nous avait fournie s'arrêtait là. Il vous faut peut-être la compléter, et je ne saurais trop vous conseiller de bien vérifier la validité de la clé que vous utiliserez avant de l'utiliser comme source. Il ne faudrait pas que ce fichier invalide soit encore en circulation.

**Comment by laurentfloch** [comment]
Bonjour Pascal,
Est-ce que tu pourrais nous retrouver ce fichier source ?
Il est possible que la matrice t3+ soit différente de t3 fortran parce que cette version n'a pas évolué depuis 10.
C'est à vérifier.

**Comment by pascalcauquil** [comment]
J'ai 2 fichiers datant de 2009 et 2010, mais je ne me souviens absolument pas lequel a été utilisé, ni même si l'un ou l'autre ont été utilisés. Ni s'ils sont fiables.

fichier 1 : https://filesender.renater.fr/?s=download&token=1ef09fc9-b326-4ebf-b293-be635a80bd04
fichier 2 : https://filesender.renater.fr/?s=download&token=caa86cb8-ba5c-4ad5-8a3b-0acad6e922d1

**Comment by laurentfloch** [comment]
Les matrices que tu m'a envoyées et celle dont je dispose pour T3 fortran ne contiennent pas de valeurs pour les LD1 de 545 à 600 mm.
Il existe des formules de conversion, ci-dessous la documentation de l'ICCAT pour le BET.
[2_1_2_BET_ENG.pdf](https://github.com/OB7-IRD/t3/files/5807591/2_1_2_BET_ENG.pdf)

Pour ma part, je ne peux pas résoudre ce ticket qui nécessite une étude spécifique.
Il conviendrait de réattribuer ce ticket à une autre personne de l'équipe.

**Comment by laurentfloch** [comment]
Il existe des formules dans les documents de l'ICCAT. A étudier.

**Comment by laurentfloch** [comment]
J'ai ajouté la référence manquante dans la table de conversion des mesures en ld1 en lf.
Pour vérifier la valeur, le code SQL est le suivant :
SELECT * FROM specieslengthstep ld1_lf
WHERE ld1_lf.species = (SELECT topiaid FROM species WHERE code=3)
AND ld1_lf.ocean = (SELECT topiaid FROM ocean WHERE code=2)
AND ld1class = 550;
Toutes les valeurs manquantes pour le BET et l'YFT ont été ajoutée avec le script suivant :
[update_table_specieslengthstep.txt](https://github.com/OB7-IRD/t3/files/7581689/update_table_specieslengthstep.txt)
