### ISSUE TITLE
Type de données différent pour la colonne classe de taille entre T3+ (lengthclass) et AVDTH(V_LONG)

### ISSUE THREAD

**Issue by laurentfloch** [OB7-IRD/t3#45]
La comparaison des exports d'AVDTH et de t3 pour constituer la table t3_samples.sql montre des différences dans les résultats.
Dans le fichier ci-dessous, une valeur avec décimale 29.5 est arrondie à 29 dans t3.
[comparaison_lengthclass_avdth_t3.xlsx](https://github.com/OB7-IRD/t3/files/5881452/comparaison_lengthclass_avdth_t3.xlsx)

L'exploration du modèle t3 montre que le type de cette colonne est int4.
Les valeurs avec décimales sont certainement arrondies automatiquement lors de l'import des données.

Il conviendrait de modifier le modèle de la base t3 pour accepter des valeurs avec une décimale.

**Comment by MathieuDepetris** [comment]
Ticket not relevant because we will move soon to updates from Observe database
