### ISSUE TITLE
Fishing indicators independant from the statistic treatment

### ISSUE THREAD

**Issue by Antoine-Duparc** [OB7-IRD/t3#58]
**Is your feature request related to a problem? Please describe.**
Several indicators calculated in the step 1 of the T3R are indenpendent from the statical treatment of the catch and samples.

list : 
- set duration
- time at sea
- fishing time
- effort indicactors?

**Describe the solution you'd like**
It seems more suitable to move those indicators in Fishi package or elsewhere.

**Comment by MathieuDepetris** [comment]
Ticket moved into the ticket #25
