### ISSUE TITLE
proportions des échantillons aberrantes

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#6]
Les échantillons issues de T3 donnent des compositions avec autant de YFT.

**Comment by JulienLebranchu** [comment]
> <@UR50RV01L>. Salut Mathieu, J'ai vérifié la bdd ao T3_29 sur vmot5. Les échantillons donnent bien le SKJ en grands nombres par rapport aux autres espèces dans les banc objets. pour les bancs libres la figure est moins claire car il y a un mélange de BL SKJ et YFT.
<sub>[View in Slack](https://ird-ob7.slack.com/archives/CQS30CSJD/p1584953132002800)</sub>

**Comment by Antoine-Duparc** [comment]
> <@UR50RV01L>. Salut Mathieu, J'ai vérifié la bdd ao T3_29 sur vmot5. Les échantillons donnent bien le SKJ en grands nombres par rapport aux autres espèces dans les banc objets. pour les bancs libres la figure est moins claire car il y a un mélange de BL SKJ et YFT.
<sub>[View in Slack](https://ird-ob7.slack.com/archives/CQS30CSJD/p1584953132002800)</sub>

**Comment by Antoine-Duparc** [comment]
> si le soucis que nous avons ne semble toucher que les BO, cela doit provenir de la mesure FL et LD1 : soit la conversion, soit les unités (mm et cm?). bon courage pour trouver :wink:
<sub>[View in Slack](https://ird-ob7.slack.com/archives/CQS30CSJD/p1584953232004800)</sub>

**Comment by MathieuDepetris** [comment]
Salut @Antoine-Duparc merci d'avoir vérifié cela. J'ai eu quelques idées ce weekend et je pense que je vais "perdre" un peu de temps pour me créer un jeu de donnée fictif afin de trouver le beug. Ça me servira pour les tests unitaires par la suite et surtout ça me permettra d'avoir une vision plus simple de l'évolution. Je te tiens au courant dés que j'en sais plus

**Comment by Antoine-Duparc** [comment]
Salut @MathieuDepetris. oui tu vas "perdre" du temps à court terme mais tu pourrais en gagner plus tard. bon courage.

**Comment by JulienLebranchu** [comment]
Salut @MathieuDepetris, ce n'est pas perdre du temps. C'est important pour les tests unitaires, c'est même la première étape comme nous avions déjà discuté. Dis-toi que ce jeu évolura au fur et à mesure des développements. Il faut donc commencer par un jeu qui couvre le maximum de cas mais pas la totalité.

**Comment by Antoine-Duparc** [comment]
> ça m'a l'air ok Mathieu. On retrouve des proportions plus réaliste. Je continue le process jusqu'au bout pour voir. Bien joué :+1:
<sub>[View in Slack](https://ird-ob7.slack.com/archives/CQS30CSJD/p1585233469013000)</sub>

**Comment by MathieuDepetris** [comment]
Correction made in the commit d5305f1756b413a33791f22873a3b83098fe8c3b.
Small description of the correction:
- integration of the subsampling id (= sampling round, at least 1 and maximum 2 per well),
- modification of the rf4 formula (be careful, the formula in the reference methodology document "doc-traitements-t3p-v1-6" is incorrect).
