### ISSUE TITLE
Error on dbSendQuery with AVDTH 

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#73]
**Describe the bug**
From macOS, when I want load data stored in AVDTH database I have the following error 
```r
> t3::data_model_initialisation(data_source = "avdth_db",
+                                             db_con = database_con,
+                                             periode_reference = periode_reference,
+                                             countries = countries,
+                                             oceans = ocean,
+                                             sample_type = sample_type)
2023-04-12 14:35:11 - Start function data model initialisation.
[periode reference: 2018, 2019; countries: FRA, MYT; oceans: 1; sample type: 1]
2023-04-12 14:35:11 - Start trip(s) data importation from avdth database.
[]
Erreur dans dbSendQuery(conn, statement, ...) : 
  Unable to retrieve JDBC result set
  JDBC ERROR: UCAExc:::5.0.1 unexpected end of statement
  Statement: 
De plus : Message d'avis :
Dans file(con, "r") :
  file("") accepte seulement open = "w+" et open = "w+b" : utilisation du premier
```
**To Reproduce**
```r

library(t3)
library(furdeb)
config_t3 <- furdeb::configuration_file(
  path_file = "~/.appconfig/t3/20230111_130105_configuration_file.yml",
  silent = TRUE)
setwd(config_t3$wd_path)

periode_reference <- as.integer(2018:2019)
target_year <- as.integer(2018)
period_duration <- as.integer(2)
# countries for the France fleet 
countries <- c("FRA",
               "MYT")
# code 1 for the Indian Ocean
ocean <- as.integer(1)
# code 1 for landing data
sample_type <- as.integer(1)
# for french fleet YFT, SKJ, BET, ALB, MIX and LOT
species_rf1 <- as.integer(c(1, 2, 3, 4, 9, 11))
# output directories initiation
temp_output <- config_t3$output_path
if (!dir.exists(temp_output)) {
    dir.create(temp_output)
}
#final_output_path <- t3::initiate_directory(output_path = temp_output, level = "all")

db_name <- "OI_2017_2023_FRA_V35_v20220314.mdb"
db_name <- "ATL_2017_2023_V35_v20230315.mdb"
db_path<-file.path(config_t3$wd_path, db_name, fsep = "/")
database_con <- furdeb::access_dbconnection(access_db_path = paste0(db_path, ";READONLY=false"))
#database_con <- furdeb::access_dbconnection(driver_name = "access_jdbc42", access_db_path, access_jdbc42_driver_path)
DBI::dbListTables(database_con) # check connection

# output format 
output_format <- "eu"
# generation of the confidence interval
confidence_interval <- TRUE

# data model initialisation ----
t3_process <- t3::data_model_initialisation(data_source = "avdth_db",
                                            db_con = database_con,
                                            periode_reference = periode_reference,
                                            countries = countries,
                                            oceans = ocean,
                                            sample_type = sample_type)
```

**Expected behavior**
Load the data in the data frame

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by JulienLebranchu** [comment]
The issue come from a bad practice on the file path :
```r
trips_sql <- paste(readLines(con = system.file("sql\\avdth",
    "avdth_trip.sql",
    package = "t3")),
```
You must use the function `file.path()`

**Comment by VanessaRojo** [comment]
I think I've had a very similar error and I don't use a Mac. 

> config<- furdeb::configuration_file(path_file = "C:\\Users\\vanessa.rojo\\Desktop\\t3tecnica\\T3\\R_T3_2022\\test\\input\\20230411_144337_configuration_file.yml",
+                                     silent=TRUE)
> # extractions from access database ----
> database_con <- furdeb::access_dbconnection(access_db_path = config$databases_configuration$atl$database_path)
Error in RJDBC::dbConnect(access_jdbc_driver, paste0("jdbc:ucanaccess://",  : 
  Unable to connect JDBC to jdbc:ucanaccess://C:\\Users\\vanessa.rojo\\Desktop\\t3tecnica\\T3\\R_T3_2022\\data\\atot22v35_86v6.mdb
  JDBC ERROR: UCAExc:::5.0.1 given file does not exist: C:\Users\vanessa.rojo\Desktop\t3tecnica\T3\R_T3_2022\data\atot22v35_86v6.mdb

**Comment by JulienLebranchu** [comment]
@VanessaRojo , I think that it's another issue because you cannot load the database. I open a new issue. see #75

**Comment by JulienLebranchu** [comment]
@MathieuDepetris Have you merge the branch ?

**Comment by MathieuDepetris** [comment]
Corrections and updates pushed into the commit "efdbaec".
Some modifications were made according to the last version of the development branch.
For knowledge, "file.path" function is already "in" the argument of the "system.file". It's not necessary to add it to the argument but to separate each term of the argument (check the correction for further explanation).
Furthermore, tests were made for the year 2007, Atlantic Ocean until the end of the level 2 for AVDTH and t3_prod connections.
@JulienLebranchu doesn't hesitate to reopen the issue if it not work on OS system.

**Comment by JulienLebranchu** [comment]
It's work.
