### ISSUE TITLE
No correspondance with activity parameters

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#82]
DB: T3_prod
Process : 1.5

| Année | Ocean |
|-------|-------|
| 2011  | OA    |
| 2022  | OI    |
| 2021  | OI    |
| 2013  | OI    |
| 2012  | OI    |
| 2011  | OI    |
| 2010  | OI    |
| 2009  | OI    |
| 2008  | OI    |
| 2007  | OI    |
| 2006  | OI    |
| 2002  | OI    |

```
[trip: fr.ird.t3.entities.data.Trip#1562945536503#0.6452931177981799]2023-06-08 16:20:46 - 
Error: invalid "set_duration_ref" argument.
No correspondance with activity parameters (ocean and/or school type).
[trip: fr.ird.t3.entities.data.Trip#1562945536503#0.6452931177981799, activity: fr.ird.t3.entities.data.Activity#1562945536503#0.4731750670417063]
```

```
[trip: fr.ird.t3.entities.data.Trip#1562946354572#0.31608755448955794]2023-06-09 14:53:28 - 
Error: invalid "set_duration_ref" argument.
No correspondance with activity parameters (ocean and/or school type).
[trip: fr.ird.t3.entities.data.Trip#1562946354572#0.31608755448955794, activity: fr.ird.t3.entities.data.Activity#1562946354573#0.352273484073351]
```

```
trip: fr.ird.t3.entities.data.Trip#1562946508460#0.5523678810386737]
2023-06-09 15:06:55 - Error: invalid "set_duration_ref" argument.
No correspondance with activity parameters (ocean and/or school type).
[trip: fr.ird.t3.entities.data.Trip#1562946508460#0.5523678810386737, activity: fr.ird.t3.entities.data.Activity#1562946508461#0.08207885163746498]
```

```
2023-06-09 15:34:14 - Ongoing process 1.5 on item "180".
[trip: fr.ird.t3.entities.data.Trip#1562946756881#0.8618977219019106]
2023-06-09 15:34:14 - Error: invalid "set_duration_ref" argument.
No correspondance with activity parameters (ocean and/or school type).
[trip: fr.ird.t3.entities.data.Trip#1562946756881#0.8618977219019106, activity: fr.ird.t3.entities.data.Activity#1562946756882#0.13715039461774337]
```
--

--

**Comment by laurentfloch** [comment]
J'ai rechargé les bases AVDTH 2022 et 2023.
Je vous invite à refaire un essai.
Pourriez-vous me donner plus de précisions ?

**Comment by JulienLebranchu** [comment]
@laurentfloch, it concerns 2000 and 2006. You need to update t3_prod for "set_duration_ref" argument.

**Comment by JulienLebranchu** [comment]
@laurentfloch  you need to check the set_duration table for all year. In January, I had no issue on the period 2012 - 2022 for both ocean. Now I have an issue for 2021 and 2022 in IO.

**Comment by JulienLebranchu** [comment]
I check the T3_prod database. It seems that the setduration table is complete.
@MathieuDepetris maybe you have to inspect the R code.

```SQL

select c.label1 , sd."year",  o.label1, count(st.label1) from setduration sd
inner join country c on sd.country = c.topiaid and c.label1 = 'France'
inner join ocean o on sd.ocean = o.topiaid
inner join schooltype  st on sd.schooltype  = st.topiaid
group by c.label1 , sd."year",  o.label1
```

## Result:

| country | year | ocean      | count |
|---------|------|------------|-------|
| France  | 1981 | Indien     | 2     |
| France  | 1982 | Indien     | 2     |
| France  | 1983 | Indien     | 2     |
| France  | 1984 | Indien     | 2     |
| France  | 1985 | Indien     | 2     |
| France  | 1986 | Indien     | 2     |
| France  | 1987 | Indien     | 2     |
| France  | 1988 | Indien     | 2     |
| France  | 1989 | Indien     | 2     |
| France  | 1990 | Atlantique | 2     |
| France  | 1990 | Indien     | 2     |
| France  | 1991 | Atlantique | 2     |
| France  | 1991 | Indien     | 2     |
| France  | 1992 | Atlantique | 2     |
| France  | 1992 | Indien     | 2     |
| France  | 1993 | Atlantique | 2     |
| France  | 1993 | Indien     | 2     |
| France  | 1994 | Atlantique | 2     |
| France  | 1994 | Indien     | 2     |
| France  | 1995 | Atlantique | 2     |
| France  | 1995 | Indien     | 2     |
| France  | 1996 | Atlantique | 2     |
| France  | 1996 | Indien     | 2     |
| France  | 1997 | Atlantique | 2     |
| France  | 1997 | Indien     | 2     |
| France  | 1998 | Atlantique | 3     |
| France  | 1998 | Indien     | 3     |
| France  | 1999 | Atlantique | 3     |
| France  | 1999 | Indien     | 3     |
| France  | 2000 | Atlantique | 3     |
| France  | 2000 | Indien     | 3     |
| France  | 2001 | Atlantique | 3     |
| France  | 2001 | Indien     | 3     |
| France  | 2002 | Atlantique | 3     |
| France  | 2002 | Indien     | 3     |
| France  | 2003 | Atlantique | 3     |
| France  | 2003 | Indien     | 3     |
| France  | 2004 | Atlantique | 3     |
| France  | 2004 | Indien     | 3     |
| France  | 2005 | Atlantique | 3     |
| France  | 2005 | Indien     | 3     |
| France  | 2006 | Atlantique | 3     |
| France  | 2006 | Indien     | 3     |
| France  | 2007 | Atlantique | 3     |
| France  | 2007 | Indien     | 3     |
| France  | 2008 | Atlantique | 3     |
| France  | 2008 | Indien     | 3     |
| France  | 2009 | Atlantique | 3     |
| France  | 2009 | Indien     | 3     |
| France  | 2010 | Atlantique | 3     |
| France  | 2010 | Indien     | 3     |
| France  | 2011 | Atlantique | 3     |
| France  | 2011 | Indien     | 3     |
| France  | 2012 | Atlantique | 3     |
| France  | 2012 | Indien     | 3     |
| France  | 2013 | Atlantique | 3     |
| France  | 2013 | Indien     | 3     |
| France  | 2014 | Atlantique | 3     |
| France  | 2014 | Indien     | 3     |
| France  | 2015 | Atlantique | 3     |
| France  | 2015 | Indien     | 3     |
| France  | 2016 | Atlantique | 3     |
| France  | 2016 | Indien     | 3     |
| France  | 2017 | Atlantique | 3     |
| France  | 2017 | Indien     | 3     |
| France  | 2018 | Atlantique | 3     |
| France  | 2018 | Indien     | 3     |
| France  | 2019 | Atlantique | 3     |
| France  | 2019 | Indien     | 3     |
| France  | 2020 | Atlantique | 3     |
| France  | 2020 | Indien     | 3     |
| France  | 2021 | Atlantique | 3     |
| France  | 2021 | Indien     | 3     |
| France  | 2022 | Atlantique | 3     |
| France  | 2022 | Indien     | 3     |

**Comment by MathieuDepetris** [comment]
Ticket close because we will move to inputs from Observe database, but we have to keep a look on that for the test on Observe database
