### ISSUE TITLE
Dataset with catch_weight value negative

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#85]
Year : 2001
Ocean : OI
DB: T3_prod

The catch_weight value is negative.
```
[elementarycatch: fr.ird.t3.entities.data.ElementaryCatch#1562945402029#0.5889291586686802]2023-06-08 16:09:55 - Error: invalide "catch_weight" argument, positive value expected.
```

**Comment by JulienLebranchu** [comment]
@laurentfloch You should look the logbook:

`select * from elementarycatch e 
inner join weightcategorylogbook w on w.topiaid = e.weightcategorylogbook
inner join species s on s.topiaid = w.species 
where e.topiaid = 'fr.ird.t3.entities.data.ElementaryCatch#1562945402029#0.5889291586686802'`

**Comment by laurentfloch** [comment]
Ce n'est pas une valeur négative mais à 0 dans la base AVDTH et dans t3_proD.
Il faudrait vérifier le code de ce contrôle.

Dans le logbook, c'était un ligne associée à deux calées et les tonnages ont été répartis.
Pour le BET, 1 tonne a été déclarée sur 1 calée et 0 sur l'autre.
J'ai modifié la base pour déclarer 0.5 tonnes à chaque calée.

**Comment by MathieuDepetris** [comment]
Ticket close because t3_prod will be not used anymore, but we have to take a look on that when we will use inputs from Observe database
