### ISSUE TITLE
Process stop on 2.3 without error

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#86]
Year : 2007
Ocean : OA
DB : t3_prod

Process stops on 2.3 without no error information

```
[trip: fr.ird.t3.entities.data.Trip#1562946505043#0.4718976707864847]2023-06-12 16:16:19 - Ongoing process 2.3 on item "65".
[trip: fr.ird.t3.entities.data.Trip#1638782649308#0.5798946882227974]2023-06-12 16:16:19 - Process 2.3 successfull on item "65".
[trip: fr.ird.t3.entities.data.Trip#1638782649308#0.5798946882227974]
```

**Comment by MathieuDepetris** [comment]
Dear @JulienLebranchu, I've just ran the global process from the development branch and I don't have any error (the process go until the end). Could you please run again your code and check if you have again the error above. If it's not the case, please close the ticket. 
Best,
Mathieu

**Comment by MathieuDepetris** [comment]
Close because t3_prod will be no longer use as inputs. Be careful on the test that we will do on inputs from Observe database
