### ISSUE TITLE
Process stops on 2.5 without no error information

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/t3#87]
Process stops on 2.5 without no error information
DB : t3_prod

| Année | Ocean |
|-------|-------|
| 2018  | OA    |
| 2017  | OA    |
| 2012  | OA    |
| 2009  | OA    |
| 2004  | OA    |
| 2014  | OI    |
| 2010  | OI    |
| 2009  | OI    |
| 2008  | OI    |
| 2007  | OI    |
| 2006  | OI    |
| 2002  | OI    |

Example of issue : 
```
[trip: fr.ird.t3.entities.data.Trip#1562948036745#0.8460101258328447]2023-06-14 15:58:53 - Process 2.5 successfull on item "161".
[trip: fr.ird.t3.entities.data.Trip#1562948036745#0.8460101258328447]
``

**Comment by MathieuDepetris** [comment]
Checking:
- [ ] 2018 - OA
- [ ] 2017 - OA
- [ ] 2012 - OA
- [ ] 2009 - OA
- [ ] 2004 - OA
- [ ] 2014 - OI
- [ ] 2010 - OI
- [ ] 2009 - OI
- [ ] 2008 - OI
- [ ] 2007 - OI
- [ ] 2006 - OI
- [ ] 2002 - OI

**Comment by MathieuDepetris** [comment]
For year 2018 - OA, error at level 2.5

<img width="409" alt="Capture d’écran 2023-07-12 152852" src="https://github.com/OB7-IRD/t3/assets/35579752/53e7a313-f7ad-41d5-b919-fc0cd8bc3832">

**Comment by MathieuDepetris** [comment]
For year 2009 - OA, same kind of error that above

<img width="407" alt="Capture d’écran 2023-07-12 152852" src="https://github.com/OB7-IRD/t3/assets/35579752/41adf504-0ab6-4f5d-a5a2-f62e8f94a6de">

**Comment by MathieuDepetris** [comment]
Problem solved. The issue was related to the extraction process of 2.5 data and the sample id which can contain multiple sample ids. The correction was applied in the process 2.8 too.

**Comment by MathieuDepetris** [comment]
Checking:
- [ ] 2018 - OA
- [ ] 2017 - OA
- [ ] 2012 - OA
- [ ] 2009 - OA
- [ ] 2004 - OA
- [ ] 2014 - OI
- [ ] 2010 - OI
- [ ] 2009 - OI
- [ ] 2008 - OI
- [ ] 2007 - OI
- [ ] 2006 - OI
- [ ] 2002 - OI

**Comment by MathieuDepetris** [comment]
All years checked, problem solved.
