### ISSUE TITLE
No code "MYT" in the table setduration (db t3_prod)

### ISSUE THREAD

**Issue by MathieuDepetris** [OB7-IRD/t3#89]
Dear Laurent,
This is very strange but I don't see any lines related to the country Mayotte (code MYT) in the table setduration  of the database t3_prod. When you have time, could you please add the lines associated with this country in the table.
Best,
Mat

**Comment by laurentfloch** [comment]
Dear Mathieu,
For the flag Mayotte, you have to select parameters for the fleet 'France'.
Regards,
Laurent

**Comment by MathieuDepetris** [comment]
Thank Laurent for your quick answer.
So far the process (t3r) associates the country modality defines by the user with the reference table setduration. Like you propose I can make a shortcut and associate Mayotte parameters with the French parameters but I think it's not the correct way to do. I think that if we want to have a generic process we have to keep setduraction parameters "country by country". In any case we don't have to rush on those issues and we can discuss that directly if you prefer.
Mat

**Comment by laurentfloch** [comment]
In the previous version of t3, the parameters were group by fleet.

But, the new t3 team has to define the new rule, no problem.
I propose to discuss about that with other colleagues during the next meeting.

Laurent

**Comment by MathieuDepetris** [comment]
I close this comment because we will use Observe database instead of t3_prod database for the inputs, but we have to stay sharp when we will do our tests.
Mathieu
